/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthToken
 */
export interface OAuthToken {
    /**
     * 
     * @type {string}
     * @memberof OAuthToken
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthToken
     */
    expiresIn: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthToken
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the OAuthToken interface.
 */
export function instanceOfOAuthToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "expiresIn" in value;
    isInstance = isInstance && "refreshToken" in value;

    return isInstance;
}

export function OAuthTokenFromJSON(json: any): OAuthToken {
    return OAuthTokenFromJSONTyped(json, false);
}

export function OAuthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'refreshToken': json['refresh_token'],
    };
}

export function OAuthTokenToJSON(value?: OAuthToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'expires_in': value.expiresIn,
        'refresh_token': value.refreshToken,
    };
}

