/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PixivToken
 */
export interface PixivToken {
    /**
     * 
     * @type {string}
     * @memberof PixivToken
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof PixivToken
     */
    expiresIn: string;
    /**
     * 
     * @type {string}
     * @memberof PixivToken
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PixivToken
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof PixivToken
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof PixivToken
     */
    username: string;
}

/**
 * Check if a given object implements the PixivToken interface.
 */
export function instanceOfPixivToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "expiresIn" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function PixivTokenFromJSON(json: any): PixivToken {
    return PixivTokenFromJSONTyped(json, false);
}

export function PixivTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): PixivToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'name': json['name'],
        'refreshToken': json['refresh_token'],
        'userId': json['user_id'],
        'username': json['username'],
    };
}

export function PixivTokenToJSON(value?: PixivToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'expires_in': value.expiresIn,
        'name': value.name,
        'refresh_token': value.refreshToken,
        'user_id': value.userId,
        'username': value.username,
    };
}

