/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReferenceImage
 */
export interface ReferenceImage {
    /**
     * 
     * @type {string}
     * @memberof ReferenceImage
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceImage
     */
    link: string;
}

/**
 * Check if a given object implements the ReferenceImage interface.
 */
export function instanceOfReferenceImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "link" in value;

    return isInstance;
}

export function ReferenceImageFromJSON(json: any): ReferenceImage {
    return ReferenceImageFromJSONTyped(json, false);
}

export function ReferenceImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': json['image'],
        'link': json['link'],
    };
}

export function ReferenceImageToJSON(value?: ReferenceImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'link': value.link,
    };
}

