/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SNSPostResponse
 */
export interface SNSPostResponse {
    /**
     * 
     * @type {string}
     * @memberof SNSPostResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the SNSPostResponse interface.
 */
export function instanceOfSNSPostResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SNSPostResponseFromJSON(json: any): SNSPostResponse {
    return SNSPostResponseFromJSONTyped(json, false);
}

export function SNSPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SNSPostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function SNSPostResponseToJSON(value?: SNSPostResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

