/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetImage } from './TweetImage';
import {
    TweetImageFromJSON,
    TweetImageFromJSONTyped,
    TweetImageToJSON,
} from './TweetImage';

/**
 * 
 * @export
 * @interface TweetImagesResponse
 */
export interface TweetImagesResponse {
    /**
     * 
     * @type {Array<TweetImage>}
     * @memberof TweetImagesResponse
     */
    images: Array<TweetImage>;
}

/**
 * Check if a given object implements the TweetImagesResponse interface.
 */
export function instanceOfTweetImagesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "images" in value;

    return isInstance;
}

export function TweetImagesResponseFromJSON(json: any): TweetImagesResponse {
    return TweetImagesResponseFromJSONTyped(json, false);
}

export function TweetImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetImagesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'images': ((json['images'] as Array<any>).map(TweetImageFromJSON)),
    };
}

export function TweetImagesResponseToJSON(value?: TweetImagesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'images': ((value.images as Array<any>).map(TweetImageToJSON)),
    };
}

