/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetImage
 */
export interface TweetImage {
    /**
     * 
     * @type {string}
     * @memberof TweetImage
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof TweetImage
     */
    mediaUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TweetImage
     */
    tweetId: string;
}

/**
 * Check if a given object implements the TweetImage interface.
 */
export function instanceOfTweetImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "link" in value;
    isInstance = isInstance && "mediaUrl" in value;
    isInstance = isInstance && "tweetId" in value;

    return isInstance;
}

export function TweetImageFromJSON(json: any): TweetImage {
    return TweetImageFromJSONTyped(json, false);
}

export function TweetImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': json['link'],
        'mediaUrl': json['media_url'],
        'tweetId': json['tweet_id'],
    };
}

export function TweetImageToJSON(value?: TweetImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'link': value.link,
        'media_url': value.mediaUrl,
        'tweet_id': value.tweetId,
    };
}

