/* tslint:disable */
/* eslint-disable */
/**
 * SNS-Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TwitterToken
 */
export interface TwitterToken {
    /**
     * 
     * @type {string}
     * @memberof TwitterToken
     */
    accessSecret: string;
    /**
     * 
     * @type {string}
     * @memberof TwitterToken
     */
    accessToken: string;
}

/**
 * Check if a given object implements the TwitterToken interface.
 */
export function instanceOfTwitterToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessSecret" in value;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function TwitterTokenFromJSON(json: any): TwitterToken {
    return TwitterTokenFromJSONTyped(json, false);
}

export function TwitterTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwitterToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessSecret': json['access_secret'],
        'accessToken': json['access_token'],
    };
}

export function TwitterTokenToJSON(value?: TwitterToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_secret': value.accessSecret,
        'access_token': value.accessToken,
    };
}

